name: C/C++ CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch: # manual build

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
#    - name: configure
#      run: ./configure
    - name: Main Build Linux
      run: make
    - name: Pre-Test Install Google Test
      run: sudo apt-get install libgtest-dev
    - name: Build Tests
      run:  make tests
    - name: Run Tests
      run: make runtests
#    - name: make distcheck
#      run: make distcheck

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
#    - name: configure
#      run: ./configure
    - name: Main Build MacOS
      run: make
    - name: Configure Google Test
      run: |
        brew update
        brew install googletest
    - name: Build Tests
      run: make tests
    - name: Run Tests
      run: make runtests
#    - name: make distcheck
#      run: make distcheck
