name: C/C++ CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch: # manual build

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
#    - name: configure
#      run: ./configure
    - name: Main Build Linux
      run: make
    - name: Test Linux
      run:  |
        make tests V=1
        make runtests
#    - name: make distcheck
#      run: make distcheck

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
#    - name: configure
#      run: ./configure
    - name: Main Build MacOS
      run: make
    - name: Test MacOS
      run: |
        make tests V=1
        make runtests
#    - name: make distcheck
#      run: make distcheck
